# Generated by Django 5.1.2 on 2024-10-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('phone_number', models.IntegerField()),
                ('donation_amout', models.IntegerField()),
                ('org_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('personal', 'personal'), ('legal', 'legal')], max_length=255)),
                ('status', models.CharField(choices=[('new', 'yangi'), ('modernation', 'modernation'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='new', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('karta_orqali', 'karta_orqali'), ('naqd', 'naqd')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('student_type', models.CharField(choices=[('new', 'yangi'), ('old', 'eski'), ('recent', 'yaqinda')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='OTM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.university'),
        ),
    ]
